FROM node:10.16.0-alpine
RUN mkdir -p /app/config /app/src
WORKDIR /app
 #ignore if don't have react with typescript
COPY tsconfig.json /app/tsconfig.json
#ignore if don't have react with typescript
COPY tslint.json /app/tslint.json 
COPY package.json /app/package.json
COPY docker.env /app/.env
COPY package-lock.json /app/package-lock.json
RUN npm install
CMD ["npm", "run", "dev"]